# Generated by Django 3.2.7 on 2021-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('1', 'English'), ('2', 'Tamil'), ('3', 'Hindi'), ('4', 'Telugu'), ('5', 'Malayalam')], default='1', help_text='Enter the language', max_length=1),
        ),
    ]
